devices:
  vqfx1:
    platform: vqfx
    ip: 10.54.13.14
    auth:
      username: admin
      password: juniper1
    script_user: admin
    ssh_trust: null
    macsec:
      ca_name: CA1
      mode: qkd
    links:
    - peer: vqfx2
      peer_ip: 10.54.12.193
      peer_interface: xe-0/0/1
      peer_sae: sae_002
      role: master
      interface: xe-0/0/1
      ca_names:
      - CA1
      - CA2
    qkd:
      sae_id: sae_001
    kme:
      ip: 100.100.100.10
  vqfx2:
    platform: vqfx
    ip: 10.54.12.193
    auth:
      username: admin
      password: juniper1
    script_user: admin
    ssh_trust: null
    macsec:
      ca_name: CA1
      mode: qkd
    links:
    - peer: vqfx1
      peer_ip: 10.54.13.14
      peer_interface: xe-0/0/1
      peer_sae: sae_001
      role: slave
      interface: xe-0/0/1
      ca_names:
      - CA1
      - CA2
    qkd:
      sae_id: sae_002
    kme:
      ip: 100.100.100.11
