from pathlib import Path
from lib.settings import CONFIG, PKI

def print_manual_kme_copy_instructions(profile):
    """
    Print manual copy instructions for installing generated KME certificates
    when kme_orchestrator.py is not used.

    qkd_orchestrator owns PKI generation.
    KME-side manual copy only installs already generated material.
    """

    kme_default_dest = "~/kme-lab/etsi-gs-qkd-014-referenceimplementation/certs"

    print("")
    print("============================================================")
    print("Manual KME certificate installation instructions")
    print("============================================================")
    print("")
    print("Use these commands only if kme_orchestrator.py is NOT used.")
    print("")
    print("Target KME cert directory:")
    print(f"  {kme_default_dest}")
    print("")

    if profile == "self_signed":

        self_signed_dir = Path(CONFIG["self_signed_dir"])
        root_ca = self_signed_dir / PKI["SELF_SIGNED_CA_CERT_NAME"]
        kme_dir = self_signed_dir / "kme"

        print("PKI profile: self_signed")
        print("")
        print("Files generated by qkd_orchestrator:")
        print(f"  {root_ca}")
        print(f"  {kme_dir}/kme_001.crt")
        print(f"  {kme_dir}/kme_001.key")
        print(f"  {kme_dir}/kme_001.pem")
        print(f"  {kme_dir}/kme_002.crt")
        print(f"  {kme_dir}/kme_002.key")
        print(f"  {kme_dir}/kme_002.pem")
        print("  ...")
        print("")
        print("Manual local copy example:")
        print("")
        print(f"mkdir -p {kme_default_dest}")
        print(f"cp {root_ca} {kme_default_dest}/root.crt")
        print(f"cp {kme_dir}/kme_*.crt {kme_default_dest}/")
        print(f"cp {kme_dir}/kme_*.key {kme_default_dest}/")
        print(f"cp {kme_dir}/kme_*.pem {kme_default_dest}/")
        print("")
        print("Recommended permissions:")
        print("")
        print(f"chmod 644 {kme_default_dest}/*.crt")
        print(f"chmod 600 {kme_default_dest}/*.key")
        print(f"chmod 600 {kme_default_dest}/*.pem")
        print("")
        print("Remote copy example:")
        print("")
        print("KME_HOST=<kme-host-ip>")
        print(f"ssh root@$KME_HOST 'mkdir -p {kme_default_dest}'")
        print(f"scp {root_ca} root@$KME_HOST:{kme_default_dest}/root.crt")
        print(f"scp {kme_dir}/kme_*.crt root@$KME_HOST:{kme_default_dest}/")
        print(f"scp {kme_dir}/kme_*.key root@$KME_HOST:{kme_default_dest}/")
        print(f"scp {kme_dir}/kme_*.pem root@$KME_HOST:{kme_default_dest}/")
        print("")
        print("Do NOT copy the self-signed Root CA private key unless you explicitly")
        print("need to sign new certificates on the KME host.")
        print("Runtime KME containers should only need root.crt and leaf cert/key/pem.")
        print("")

    elif profile == "hierarchical_ca":

        hierarchical_dir = Path(CONFIG["hierarchical_dir"])
        kme_certs_dir = hierarchical_dir / "kme_pki" / "certs"
        install_on_kme_dir = hierarchical_dir / "trust_exchange" / "install_on_kme"

        print("PKI profile: hierarchical_ca")
        print("")
        print("Files generated by qkd_orchestrator:")
        print(f"  {kme_certs_dir}/kme_001/kme_001.crt")
        print(f"  {kme_certs_dir}/kme_001/kme_001.key")
        print(f"  {kme_certs_dir}/kme_001/kme_001.pem")
        print(f"  {kme_certs_dir}/kme_001/kme_001.chain.crt")
        print(f"  {kme_certs_dir}/kme_002/kme_002.crt")
        print(f"  {kme_certs_dir}/kme_002/kme_002.key")
        print(f"  {kme_certs_dir}/kme_002/kme_002.pem")
        print(f"  {kme_certs_dir}/kme_002/kme_002.chain.crt")
        print("  ...")
        print("")
        print("Trust material for KME:")
        print(f"  {install_on_kme_dir}/trusted-juniper-ca-bundle.crt")
        print(f"  {install_on_kme_dir}/juniper-root-ca.crt")
        print(f"  {install_on_kme_dir}/juniper-issuing-ca.crt")
        print("")
        print("Manual local copy example:")
        print("")
        print(f"mkdir -p {kme_default_dest}")
        print(f"cp {kme_certs_dir}/kme_*/*.crt {kme_default_dest}/")
        print(f"cp {kme_certs_dir}/kme_*/*.key {kme_default_dest}/")
        print(f"cp {kme_certs_dir}/kme_*/*.pem {kme_default_dest}/")
        print(f"cp {kme_certs_dir}/kme_*/*.chain.crt {kme_default_dest}/")
        print(f"cp {install_on_kme_dir}/*.crt {kme_default_dest}/")
        print("")
        print("Recommended permissions:")
        print("")
        print(f"chmod 644 {kme_default_dest}/*.crt")
        print(f"chmod 600 {kme_default_dest}/*.key")
        print(f"chmod 600 {kme_default_dest}/*.pem")
        print("")
        print("Remote copy example:")
        print("")
        print("KME_HOST=<kme-host-ip>")
        print(f"ssh root@$KME_HOST 'mkdir -p {kme_default_dest}'")
        print(f"scp {kme_certs_dir}/kme_*/*.crt root@$KME_HOST:{kme_default_dest}/")
        print(f"scp {kme_certs_dir}/kme_*/*.key root@$KME_HOST:{kme_default_dest}/")
        print(f"scp {kme_certs_dir}/kme_*/*.pem root@$KME_HOST:{kme_default_dest}/")
        print(f"scp {kme_certs_dir}/kme_*/*.chain.crt root@$KME_HOST:{kme_default_dest}/")
        print(f"scp {install_on_kme_dir}/*.crt root@$KME_HOST:{kme_default_dest}/")
        print("")
        print("Do NOT copy KME Root CA private key or KME Issuing CA private key.")
        print("Those are CA signing keys and should not be needed by the KME runtime.")
        print("")

    else:
        raise ValueError(f"Unsupported PKI profile: {profile}")

    print("After manual copy, restart the KME containers if needed:")
    print("")
    print("cd ~/kme-lab/etsi-gs-qkd-014-referenceimplementation")
    print("docker compose -f docker-compose-kme.yml down -v")
    print("docker compose -f docker-compose-kme.yml up -d")
    print("")
    print("============================================================")
    print("")
