system:
  maxthreads: 1

  event_options:
    start_time: "2026-07-07.13:00:00"

secrets:
  username: admin
  password: juniper1

CA_server:

  CA_cert:
    fetch: false
    generate: false

  c_a: QKD_CA1

  ca_server_ip: 100.123.0.8

  ca_path: /root/qkd-certs/
  ca_cert_name: root.crt
  ca_key_name: root.key

  ca_user: root
  ca_pass: juniper1

qkd_roles:
  master: acx7348-p1
  slave: acx7332-p1
  additional_slave_SAE_IDs: []

acx7348-p1:
  ip: 100.123.170.202
  interfaces:
    - et-2/0/4
  kme:
    kme_name: https://100.123.252.10
    kme_port: 8443

acx7332-p1:
  ip: 100.123.170.201
  interfaces:
    - et-2/0/0
  kme:
    kme_name: https://100.123.252.11
    kme_port: 8443