#!/usr/bin/env python3
"""
lib/kme/cert_install.py

Install KME certificate material on the remote ETSI KME host.

Scope:
- read active PKI profile generated by qkd_orchestrator.py
- collect KME certificate material from local certs directory
- validate KME certificate SAN IP entries
- stage runtime-compatible files
- clean remote ETSI certs directory
- upload staged certificate material to remote ETSI certs directory
- set remote permissions
- update KME state

This module does not:
- generate certificates
- build Docker images
- create Docker networks
- run docker compose up
- restart containers
"""

from __future__ import annotations

import argparse
import datetime as dt
import shutil
import shlex
import subprocess
import tempfile
from pathlib import Path
from typing import Any

import yaml

from lib.kme.compose import load_yaml as load_kme_yaml
from lib.kme.state import (
    get_bootstrap_completed,
    load_state,
    state_exists,
    update_state,
)

try:
    from lib.common.config import load_runtime_pki_profile
except ModuleNotFoundError:
    from lib.config import load_runtime_pki_profile

try:
    from lib.common.settings import CONFIG, PKI
except ModuleNotFoundError:
    from lib.settings import CONFIG, PKI


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CONFIG = REPO_ROOT / "config" / "kme" / "lab.yaml"


def require(config: dict[str, Any], *keys: str) -> Any:
    current: Any = config

    for key in keys:
        if not isinstance(current, dict) or key not in current:
            raise KeyError(f"Missing required config key: {'.'.join(keys)}")
        current = current[key]

    return current


def shell_quote(value: Any) -> str:
    return shlex.quote(str(value))


def run_command(
    cmd: list[str],
    dry_run: bool = False,
    check: bool = True,
    capture: bool = False,
) -> subprocess.CompletedProcess:
    cmd = [str(item) for item in cmd]

    if dry_run:
        print("[DRY-RUN]", " ".join(cmd))
        return subprocess.CompletedProcess(
            args=cmd,
            returncode=0,
            stdout="",
            stderr="",
        )

    print("->", " ".join(cmd))

    return subprocess.run(
        cmd,
        text=True,
        check=check,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
    )


def get_ssh_alias(config: dict[str, Any]) -> str:
    return str(require(config, "ssh", "host_alias"))


def get_ssh_key_name(config: dict[str, Any]) -> str:
    return str(require(config, "ssh", "key_name"))


def get_ssh_key_path(config: dict[str, Any]) -> Path:
    return Path.home() / ".ssh" / get_ssh_key_name(config)


def get_strict_host_key_checking(config: dict[str, Any]) -> str:
    return str(config.get("ssh", {}).get("strict_host_key_checking", "no"))


def ssh_base_cmd(
    config: dict[str, Any],
    batch: bool = True,
    include_identity: bool = True,
) -> list[str]:
    cmd = [
        "ssh",
        "-o",
        f"StrictHostKeyChecking={get_strict_host_key_checking(config)}",
    ]

    if batch:
        cmd.extend(["-o", "BatchMode=yes"])

    key_path = get_ssh_key_path(config)

    if include_identity and key_path.exists():
        cmd.extend(["-i", str(key_path), "-o", "IdentitiesOnly=yes"])

    cmd.append(get_ssh_alias(config))
    return cmd


def scp_base_cmd(config: dict[str, Any]) -> list[str]:
    cmd = [
        "scp",
        "-O",
        "-o",
        f"StrictHostKeyChecking={get_strict_host_key_checking(config)}",
        "-o",
        "BatchMode=yes",
    ]

    key_path = get_ssh_key_path(config)

    if key_path.exists():
        cmd.extend(["-i", str(key_path), "-o", "IdentitiesOnly=yes"])

    return cmd


def remote_run(
    config: dict[str, Any],
    command: str,
    dry_run: bool = False,
    check: bool = True,
    capture: bool = False,
) -> subprocess.CompletedProcess:
    return run_command(
        ssh_base_cmd(config) + [command],
        dry_run=dry_run,
        check=check,
        capture=capture,
    )


def remote_copy_file(
    config: dict[str, Any],
    local_file: str | Path,
    remote_dir: str,
    dry_run: bool = False,
) -> None:
    cmd = scp_base_cmd(config) + [
        str(local_file),
        f"{get_ssh_alias(config)}:{remote_dir}/",
    ]

    run_command(cmd, dry_run=dry_run, check=True)


def load_state_for_cert_install(
    config: dict[str, Any],
    dry_run: bool = False,
) -> dict[str, Any]:
    if state_exists(config):
        state = load_state(config)

        if get_bootstrap_completed(state):
            return state

        if not dry_run:
            raise RuntimeError("Bootstrap state is not completed. Run bootstrap first.")

        print("[DRY-RUN] Bootstrap state exists but is not completed; continuing for dry-run")
        return state

    if dry_run:
        print("[DRY-RUN] KME state file is missing; continuing with config-only dry-run")
        return {}

    raise RuntimeError("KME state file is missing. Run bootstrap first.")


def verify_build_env_ready(state: dict[str, Any], dry_run: bool = False) -> None:
    completed = bool(state.get("build_env", {}).get("completed", False))

    if completed:
        return

    if dry_run:
        print("[DRY-RUN] build-env state missing or incomplete; continuing for dry-run")
        return

    raise RuntimeError("build-env is not completed. Run build-env first.")


def get_certs_dir(config: dict[str, Any]) -> str:
    return str(require(config, "paths", "certs_dir"))


def get_active_pki_profile() -> str:
    runtime_pki = load_runtime_pki_profile()

    if not isinstance(runtime_pki, dict):
        raise RuntimeError("Invalid runtime PKI profile format")

    profile = runtime_pki.get("pki", {}).get("profile")

    if not profile:
        profile = runtime_pki.get("profile")

    if not profile:
        raise RuntimeError("Unable to determine active PKI profile from runtime config")

    return str(profile)


def resolve_repo_path(value: str | Path) -> Path:
    path = Path(str(value)).expanduser()

    if path.is_absolute():
        return path

    return REPO_ROOT / path


def assert_file(path: str | Path, description: str) -> Path:
    path = resolve_repo_path(path)

    if not path.exists():
        raise FileNotFoundError(f"Missing {description}: {path}")

    if not path.is_file():
        raise RuntimeError(f"Expected file for {description}, got: {path}")

    return path


def assert_dir(path: str | Path, description: str) -> Path:
    path = resolve_repo_path(path)

    if not path.exists():
        raise FileNotFoundError(f"Missing {description}: {path}")

    if not path.is_dir():
        raise RuntimeError(f"Expected directory for {description}, got: {path}")

    return path


def self_signed_dir() -> Path:
    return resolve_repo_path(CONFIG["self_signed_dir"])


def hierarchical_dir() -> Path:
    return resolve_repo_path(CONFIG["hierarchical_dir"])


def self_signed_kme_dir() -> Path:
    return self_signed_dir() / "kme"


def self_signed_root_ca_cert() -> Path:
    return self_signed_dir() / PKI["SELF_SIGNED_CA_CERT_NAME"]


def hierarchical_kme_certs_dir() -> Path:
    return hierarchical_dir() / "kme_pki" / "certs"


def hierarchical_install_on_kme_dir() -> Path:
    return hierarchical_dir() / "trust_exchange" / "install_on_kme"


def copy_file_to_stage(source: Path, stage_dir: Path, target_name: str | None = None) -> Path:
    target = stage_dir / (target_name if target_name else source.name)
    shutil.copy2(source, target)
    return target


def stage_self_signed_material(stage_dir: Path) -> list[Path]:
    source_dir = assert_dir(self_signed_kme_dir(), "self-signed KME cert directory")
    root_ca = assert_file(self_signed_root_ca_cert(), "self-signed Root CA certificate")

    staged: list[Path] = []
    staged.append(copy_file_to_stage(root_ca, stage_dir, target_name="root.crt"))

    for source in sorted(source_dir.iterdir()):
        if not source.is_file():
            continue

        if source.suffix not in {".crt", ".key", ".pem"}:
            continue

        staged.append(copy_file_to_stage(source, stage_dir))

    if len(staged) <= 1:
        raise RuntimeError(f"No self-signed KME cert files found in: {source_dir}")

    return staged


def stage_hierarchical_material(stage_dir: Path) -> list[Path]:
    certs_dir = assert_dir(hierarchical_kme_certs_dir(), "hierarchical KME certs directory")
    trust_dir = assert_dir(hierarchical_install_on_kme_dir(), "hierarchical KME trust directory")

    staged: list[Path] = []

    for device_dir in sorted(certs_dir.iterdir()):
        if not device_dir.is_dir():
            continue

        for source in sorted(device_dir.iterdir()):
            if not source.is_file():
                continue

            if source.name.endswith((".crt", ".key", ".pem", ".chain.crt")):
                staged.append(copy_file_to_stage(source, stage_dir))

    for source in sorted(trust_dir.iterdir()):
        if source.is_file() and source.suffix == ".crt":
            staged.append(copy_file_to_stage(source, stage_dir))

    trusted_bundle = stage_dir / "trusted-juniper-ca-bundle.crt"

    if trusted_bundle.exists():
        staged.append(copy_file_to_stage(trusted_bundle, stage_dir, target_name="root.crt"))
    else:
        raise FileNotFoundError(
            f"Missing trusted-juniper-ca-bundle.crt in staged trust material: {trust_dir}"
        )

    if not staged:
        raise RuntimeError(f"No hierarchical KME cert files found in: {certs_dir}")

    return staged


def stage_certificate_material(profile: str) -> tuple[Path, list[Path]]:
    stage_dir = Path(tempfile.mkdtemp(prefix="kme-certs-"))

    if profile == "self_signed":
        staged = stage_self_signed_material(stage_dir)
    elif profile == "hierarchical_ca":
        staged = stage_hierarchical_material(stage_dir)
    else:
        raise RuntimeError(f"Unsupported PKI profile: {profile}")

    return stage_dir, staged


def cert_has_san_ip(cert_path: Path) -> bool:
    result = subprocess.run(
        [
            "openssl",
            "x509",
            "-in",
            str(cert_path),
            "-noout",
            "-text",
        ],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )

    if result.returncode != 0:
        print(f"[FAIL] openssl failed for {cert_path}")
        if result.stderr:
            print(result.stderr.strip())
        return False

    return "Subject Alternative Name" in result.stdout and "IP Address:" in result.stdout


def kme_name_prefixes() -> list[str]:
    prefix = str(PKI.get("KME_PREFIX", "kme"))
    separator = str(PKI.get("KME_SEPARATOR", "-"))
    canonical = f"{prefix}{separator}"
    legacy = f"{prefix}_" if separator != "_" else f"{prefix}-"
    if canonical == legacy:
        return [canonical]
    return [canonical, legacy]


def validate_kme_cert_san_ip(staged_files: list[Path], dry_run: bool = False) -> None:
    prefixes = tuple(kme_name_prefixes())
    certs = [
        path for path in staged_files
        if path.name.startswith(prefixes) and path.suffix == ".crt" and not path.name.endswith(".chain.crt")
    ]

    if not certs:
        raise RuntimeError("No KME leaf .crt files found for SAN IP validation")

    if dry_run:
        print(f"[DRY-RUN] Would validate SAN IP on {len(certs)} KME certificates")
        return

    failed = []

    for cert in sorted(certs):
        if cert_has_san_ip(cert):
            print(f"[OK] SAN IP present: {cert.name}")
        else:
            print(f"[FAIL] SAN IP missing: {cert.name}")
            failed.append(cert.name)

    if failed:
        raise RuntimeError("SAN IP validation failed for: " + ", ".join(failed))


def ensure_remote_cert_dir(config: dict[str, Any], dry_run: bool = False) -> None:
    certs_dir = get_certs_dir(config)
    command = f"mkdir -p {shell_quote(certs_dir)}"
    remote_run(config=config, command=command, dry_run=dry_run, check=True)


def clean_remote_cert_dir(config: dict[str, Any], dry_run: bool = False) -> None:
    certs_dir = get_certs_dir(config)

    command = (
        f"mkdir -p {shell_quote(certs_dir)} && "
        f"cd {shell_quote(certs_dir)} && "
        "rm -f "
        "root.crt "
        "kme-*.crt kme-*.key kme-*.pem kme-*.chain.crt "
        "kme_*.crt kme_*.key kme_*.pem kme_*.chain.crt "
        "trusted-juniper-ca-bundle.crt "
        "juniper-root-ca.crt "
        "juniper-issuing-ca.crt"
    )

    remote_run(config=config, command=command, dry_run=dry_run, check=True)


def upload_staged_files(
    config: dict[str, Any],
    staged_files: list[Path],
    dry_run: bool = False,
) -> None:
    certs_dir = get_certs_dir(config)

    for path in sorted(staged_files):
        remote_copy_file(
            config=config,
            local_file=path,
            remote_dir=certs_dir,
            dry_run=dry_run,
        )


def set_remote_permissions(config: dict[str, Any], dry_run: bool = False) -> None:
    certs_dir = get_certs_dir(config)

    command = (
        f"cd {shell_quote(certs_dir)} && "
        "chmod 644 *.crt 2>/dev/null || true; "
        "chmod 600 *.key 2>/dev/null || true; "
        "chmod 600 *.pem 2>/dev/null || true"
    )

    remote_run(config=config, command=command, dry_run=dry_run, check=True)


def write_cert_install_state(
    config: dict[str, Any],
    profile: str,
    staged_files: list[Path],
    dry_run: bool = False,
) -> None:
    timestamp = dt.datetime.now(dt.timezone.utc).isoformat()

    update = {
        "cert_install": {
            "completed": True,
            "timestamp_utc": timestamp,
            "profile": profile,
            "file_count": len(staged_files),
            "certs_dir": get_certs_dir(config),
        }
    }

    if dry_run:
        print("[DRY-RUN] Would update KME state with:")
        print(yaml.safe_dump(update, sort_keys=False))
        return

    update_state(config=config, updates=update)
    print("[OK] cert-install state updated")


def run_cert_install(
    config_path: str | Path,
    dry_run: bool = False,
    skip_san_validation: bool = False,
) -> dict[str, Any]:
    config = load_kme_yaml(config_path)
    state = load_state_for_cert_install(config, dry_run=dry_run)
    verify_build_env_ready(state, dry_run=dry_run)

    profile = get_active_pki_profile()

    print("=== KME cert-install ===")
    print(f"profile: {profile}")

    stage_dir, staged_files = stage_certificate_material(profile)

    print(f"staged files: {len(staged_files)}")
    print(f"stage dir   : {stage_dir}")

    if not skip_san_validation:
        validate_kme_cert_san_ip(staged_files, dry_run=dry_run)
    else:
        print("[SKIP] SAN IP validation")

    ensure_remote_cert_dir(config, dry_run=dry_run)
    clean_remote_cert_dir(config, dry_run=dry_run)
    upload_staged_files(config, staged_files, dry_run=dry_run)
    set_remote_permissions(config, dry_run=dry_run)

    write_cert_install_state(
        config=config,
        profile=profile,
        staged_files=staged_files,
        dry_run=dry_run,
    )

    print("=== KME cert-install complete ===")

    return {
        "profile": profile,
        "file_count": len(staged_files),
        "stage_dir": str(stage_dir),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Install generated KME certificates on the remote KME host",
    )

    parser.add_argument(
        "--config",
        default=str(DEFAULT_CONFIG),
        help="KME config YAML",
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show intended actions without changing anything",
    )

    parser.add_argument(
        "--skip-san-validation",
        action="store_true",
        help="Skip local SAN IP validation for KME leaf .crt files",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    run_cert_install(
        config_path=args.config,
        dry_run=args.dry_run,
        skip_san_validation=args.skip_san_validation,
    )


if __name__ == "__main__":
    main()
